### ISSUE TITLE
Compilation error saying incompatible types for getCurrentUser

### ISSUE THREAD

**Issue by siva-nadella-lab** [sourcefuse/loopback4-audit-log#107]
**Describe the bug**
I have tried to use loopback4-authentication and loopback4-auditlog and when I try to change my repository to extend from AuditRepositoryMixin, it throws the following error message. We are unsure if any step is missed out or if these are compatible libraries.

Class 'HospitalRepository' incorrectly extends base class 'DefaultCrudRepository<Hospital, any, HospitalRelations> & IAuditMixin<string>'.
  Type 'HospitalRepository' is not assignable to type 'IAuditMixin<string>'.
    The types returned by 'getCurrentUser()' are incompatible between these types.
      Type 'Promise<IAuthUser>' is not assignable to type 'Promise<User<string, string, string>>'.
        Type 'IAuthUser' is missing the following properties from type 'User<string, string, string>': permissions, authClientId, role, firstName, lastName

**To Reproduce**
Please provide a user who can review the changes in our Git repository and I can add them to view the issue.

**Comment by Tyagi-Sunny** [comment]
hii @siva-nadella-lab , add @Tyagi-Sunny & @yeshamavani

**Comment by siva-nadella-lab** [comment]
Thank you Sunny! 

Please refer to this folder. The committed code is with the compilation error.

https://github.com/siva-nadella-lab/play-arena/tree/main/ivue-referral-api-new-mongodb

**Comment by yeshamavani** [comment]
@siva-nadella-lab we will fix from our end 
but a small change that observed you need to do is 
<img width="578" alt="image" src="https://github.com/sourcefuse/loopback4-audit-log/assets/83634146/75b29fda-abb9-44f9-9423-ed8cf7174958">

this will get the same user that you are saving in your authenticate sequence step

**Comment by yeshamavani** [comment]
@siva-nadella-lab A new version is released please check and let us know if you have any further queries 
Bot has closed this issue feel free to raise a new one if required.
