### ISSUE TITLE
Need help with an error

### ISSUE THREAD

**Issue by priyadharshini-gopal** [sourcefuse/loopback4-audit-log#13]
I get the below error in my repository class where i am trying to add the auditlog. Not sure what I am missing. Please help

Class 'ContactRepository' incorrectly extends base class '{ getAuditLogRepository: () => Promise<AuditLogRepository>; getCurrentUser?: (() => Promise<{ id?: string | undefined; }>) | undefined; create(dataObject: DataObject<...>, options?: AuditOptions | undefined): Promise<...>; ... 15 more ...; count: (where?: Where<...> | undefined, options?: AnyObject | undefined) => P...'.
  Type 'ContactRepository' is not assignable to type '{ getAuditLogRepository: () => Promise<AuditLogRepository>; getCurrentUser?: (() => Promise<{ id?: string | undefined; }>) | undefined; create(dataObject: DataObject<...>, options?: AuditOptions | undefined): Promise<...>; ... 15 more ...; count: (where?: Where<...> | undefined, options?: AnyObject | undefined) => P...'.
  The types returned by 'getAuditLogRepository()' are incompatible between these types.

**Comment by akshatdubeysf** [comment]
@priyadharshini-gopal can you share your repository class ?

**Comment by priyadharshini-gopal** [comment]
Hello Akshat,

Please find attached repository class
<img width="527" alt="Repository" src="https://user-images.githubusercontent.com/43135515/145329338-9ccd3829-dfd7-4105-b2f1-ce77dc56797c.PNG">

**Comment by lchaglla** [comment]
This should fix your error

```
export class ContactRepository extends AuditRepositoryMixin<
  Contact,
  typeof Contact.prototype.id,
  ContactRelations,
  string | number, // <- Change this
  Constructor<
...
>
```

**Comment by samarpan-b** [comment]
Closing this being stale

**Comment by aaqilniz** [comment]
Hi, @samarpan-b. I am having this same issue. I have implemented an example with what I have from the docs [here](https://www.npmjs.com/package/@sourceloop/audit-log/v/4.0.1).

**Comment by yeshamavani** [comment]
@aaqilniz can you please share your repository class here

**Comment by aaqilniz** [comment]
Hi @yeshamavani. This is my repository class.

```
import { DS } from '../datasources';
import { Invoices, InvoicesRelations } from '../models';
import { AuditRepositoryMixin, IAuditMixinOptions} from "@sourceloop/audit-log";
import { Constructor, Getter, inject } from "@loopback/core";
import { repository, DefaultCrudRepository } from "@loopback/repository";
import {AuditLogRepository} from '../repositories/audit-log.repository';

interface IAuthUser {
    id?: number | string;
    username: string;
    password?: string;
}

const options = {
    actionKey: 'Invoices_Log',
} as IAuditMixinOptions;

export class InvoicesRepository extends
    AuditRepositoryMixin<
        Invoices,
        typeof Invoices.prototype.id,
        InvoicesRelations,
        string | number,
        Constructor<DefaultCrudRepository<Invoices, typeof Invoices.prototype.id, InvoicesRelations>>
    >(DefaultCrudRepository, options)
{
    constructor(
        @inject('datasources.ds') dataSource: DS, @inject.getter('security.user') public getCurrentUser: Getter<IAuthUser>, @repository.getter('AuditLogRepository') public getAuditLogRepository: Getter<AuditLogRepository>
    ) {
        super(Invoices, dataSource, getCurrentUser);
    }
}

```

I just noticed that the error message was a bit different. Maybe this is some other issue:

```
Class 'InvoicesRepository' incorrectly extends base class 'DefaultCrudRepository<Invoices, number | undefined, InvoicesRelations> & IAuditMixin<string | number>'.
  Type 'InvoicesRepository' is not assignable to type 'IAuditMixin<string | number>'.
    The types returned by 'getAuditLogRepository()' are incompatible between these types.
      Type 'Promise<AuditLogRepository>' is not assignable to type 'Promise<AuditLogRepository | AuditLogRepository>'.
        Type 'AuditLogRepository' is not assignable to type 'AuditLogRepository | AuditLogRepository'.
          Property 'auditLog' is missing in type
```


The is fixed if `AuditLogRepository` is imported from `@sourceloop/audit-log` then `audit-log.repository` (as mentioned in the readme).

**Comment by yeshamavani** [comment]
Yes if you see that the getAuditLogRepository() function of IAuditMixin returns AuditLogRepository type from this package so if you change the import should work
https://github.com/sourcefuse/loopback4-audit-log/blob/master/src/types.ts#L16

**Comment by aaqilniz** [comment]
@yeshamavani. Got it now.  I've created a small PR to update the readme to change this import [here](https://github.com/sourcefuse/loopback4-audit-log/pull/132).

**Comment by yeshamavani** [comment]
Thank you for your contribution @aaqilniz
