### ISSUE TITLE
Table name is static defined in model

### ISSUE THREAD

**Issue by parveen14** [sourcefuse/loopback4-audit-log#3]
**Describe the bug**
Table name pre-defined in model (name: 'audit_logs',). It creates issues if I want some other table name or my table name is having some prefix.
It should be configurable so that we can change it anytime without making changes in core code.

**To Reproduce**
1. Go to 'https://github.com/sourcefuse/loopback4-audit-log/blob/master/src/models/audit-log.model.ts.'
2. Check line number 13

**Expected behavior**
Table name should be configurable

**Screenshots**
![tableName](https://user-images.githubusercontent.com/12744637/112111125-ca1d1600-8bd9-11eb-98fc-1dd0c1a69d4b.png)

**Comment by akshatdubeysf** [comment]
Hi @parveen14,

According to the steps given in the [README](https://github.com/sourcefuse/loopback4-audit-log/blob/master/README.md), you can use your own model, datasource and repository for AuditLogs, and hence you can specify any name in the @model decorator. If you tried this but still getting an error, please share a screenshot of the error you are facing.

**Comment by akshatdubeysf** [comment]
@parveen14 any updates on this?

**Comment by samarpan-b** [comment]
Closing this being stale
